---
- name: Remove node | Remove Patroni DCS key from etcd
  tags: patroni
  block:
    - name: Patroni | Stop Patroni service
      ansible.builtin.systemd:
        name: patroni
        state: stopped

    - name: Patroni | Delete member key from Patroni DCS
      ansible.builtin.shell: >-
        ETCDCTL_API=3 etcdctl del /service/{{ patroni_cluster_name }}/members/{{ ansible_facts['hostname'] }}
      delegate_to: "{{ groups['patroni'] | reject('equalto', inventory_hostname) | first }}"
      register: etcd_del_result
      changed_when: etcd_del_result.stdout | int > 0

    - name: Patroni | DCS key not found (already removed)
      ansible.builtin.debug:
        msg: "Patroni DCS key for '{{ ansible_facts['hostname'] }}' was already absent."
      when: etcd_del_result.stdout | int == 0

    - name: Patroni | Shutdown the machine
      community.general.shutdown:
