---
- name: Patroni | Remove node from cluster
  ansible.builtin.include_tasks: _remove_node.yml
  when: patroni_remove_node | bool
  tags: ['etcd', 'patroni']

- name: Hostname | Upgrade hostname
  ansible.builtin.include_tasks: _hostname.yml
  when: not lab and not patroni_remove_node | bool
  tags: ['hostname', 'etcd']

- name: Apt | Install packages
  ansible.builtin.include_tasks: _apt.yml
  when: not patroni_remove_node | bool
  tags: ['apt', 'etcd']

- name: Sysctl | Manage Sysctl
  ansible.builtin.include_tasks: _sysctl.yml
  when: not patroni_remove_node | bool
  tags: ['sysctl', 'etcd']

- name: Etcd cluster | Install etcd
  ansible.builtin.include_tasks: _etcd.yml
  when: not dcs_exists | bool and not patroni_remove_node | bool
  tags: etcd

- name: PostgreSQL cluster | Install PostgreSQL cluster
  when: not patroni_remove_node | bool
  tags: ['postgresql', 'swap', 'thp', 'pam', 'ioscheduler', 'locales', 'ssh']
  block:
    - name: PostgreSQL | Install PosgreSQL
      ansible.builtin.include_tasks: _postgresql.yml
      tags: postgresql

    - name: Swap | Manage swap
      ansible.builtin.include_tasks: _swap.yml
      tags: swap

    - name: THP | Disable Transparent Huge Pages
      ansible.builtin.include_tasks: _thp.yml
      tags: thp

    - name: PAM | Manage PAM limits
      ansible.builtin.include_tasks: _pam.yml
      tags: pam

    - name: IO Scheduler | Manage IO Scheduler
      ansible.builtin.include_tasks: _ioscheduler.yml
      tags: ioscheduler

    - name: Locales | Manage locales
      ansible.builtin.include_tasks: _locales.yml
      tags: locales

    - name: SSH | Manage SSH keys
      ansible.builtin.include_tasks: _ssh.yml
      tags: ssh

- name: Balancers cluster | Install PostgreSQL cluster
  when: not patroni_remove_node | bool
  tags: ['haproxy', 'confd', 'keepalived', 'exporter']
  block:
    - name: HAProxy | Install HAProxy
      ansible.builtin.include_tasks: _haproxy.yml
      when: with_haproxy_load_balancing | bool
      tags: haproxy

    - name: Confd | Install Confd
      ansible.builtin.include_tasks: _confd.yml
      when: with_haproxy_load_balancing | bool
      tags: confd

    - name: KeepAlived | Install KeepAlived
      ansible.builtin.include_tasks: _keepalived.yml
      tags: keepalived

- name: PostgreSQL cluster | Install Patroni/PGBouncer cluster
  when: not patroni_remove_node | bool
  tags: ['pgbouncer', 'postgresql', 'patroni', 'exporter']
  block:
    - name: PGBouncer | Install PGBouncer
      ansible.builtin.include_tasks: _pgbouncer.yml
      tags: pgbouncer

    - name: PostgreSQL | Preconfigure PostgreSQL
      ansible.builtin.include_tasks: _postgresql.preconfig.yml
      tags: postgresql

    - name: Patroni | Install Patroni
      ansible.builtin.include_tasks: _patroni.yml
      tags: patroni

    - name: Patroni | Start Patroni
      ansible.builtin.include_tasks: _patroni.start.yml
      tags: patroni

    - name: PGBouncer | Configure PGBouncer
      ansible.builtin.include_tasks: _pgbouncer.config.yml
      tags: ['pgbouncer', 'exporter']

- name: Info | Get informations of cluster
  ansible.builtin.include_tasks: _info.yml
  tags: info
