---
- name: Hostname | Upgrade hostname
  include_tasks: _hostname.yml
  when: "not 'lab' in inventory_dir"
  tags: ['hostname', 'etcd']

- name: Apt | Install packages
  include_tasks: _apt.yml
  tags: ['apt', 'etcd']

- name: Sysctl | Manage Sysctl
  include_tasks: _sysctl.yml
  tags: ['sysctl', 'etcd']

- name: Etcd cluster | Install etcd
  include_tasks: _etcd.yml
  when: not dcs_exists|bool and
        (inventory_hostname in groups["patroni"]|default([]) or inventory_hostname in groups["etcd"]|default([]))
  tags: etcd

- name: PostgreSQL cluster | Install PostgreSQL cluster
  block:
    - name: PostgreSQL | Install PosgreSQL
      include_tasks: _postgresql.yml
      tags: postgresql

    - name: Swap | Manage swap
      include_tasks: _swap.yml
      tags: swap

    - name: THP | Disable Transparent Huge Pages
      include_tasks: _thp.yml
      tags: thp

    - name: PAM | Manage PAM limits
      include_tasks: _pam.yml
      tags: pam

    - name: IO Scheduler | Manage IO Scheduler
      include_tasks: _ioscheduler.yml
      tags: ioscheduler

    - name: Locales | Manage locales
      include_tasks: _locales.yml
      tags: locales

    - name: SSH | Manage SSH keys
      include_tasks: _ssh.yml
      tags: ssh
  when: (inventory_hostname in groups["patroni"]|default([]) or inventory_hostname in groups["postgresql"]|default([]))
  tags: ['postgresql', 'swap', 'thp', 'pam', 'ioscheduler', 'locales', 'ssh']

- name: Balancers cluster | Install PostgreSQL cluster
  block:
    - name: HAProxy | Install HAProxy
      include_tasks: _haproxy.yml
      tags: haproxy

    - name: Confd | Install Confd
      include_tasks: _confd.yml
      tags: confd

    - name: KeepAlived | Install KeepAlived
      include_tasks: _keepalived.yml
      tags: keepalived
  when: inventory_hostname in groups["patroni"]
  tags: ['haproxy', 'confd', 'keepalived', 'exporter']

- name: PostgreSQL cluster | Install Patroni/PGBouncer cluster
  block:
    - name: PGBouncer | Install PGBouncer
      include_tasks: _pgbouncer.yml
      tags: pgbouncer

    - name: PostgreSQL | Preconfigure PostgreSQL
      include_tasks: _postgresql.preconfig.yml
      tags: postgresql

    - name: Patroni | Install Patroni
      include_tasks: _patroni.yml
      tags: patroni

    - name: Patroni | Start Patroni
      include_tasks: _patroni.start.yml
      tags: patroni

    - name: PGBouncer | Configure PGBouncer
      include_tasks: _pgbouncer.config.yml
      tags: ['pgbouncer', 'exporter']

  when: (inventory_hostname in groups["patroni"]|default([]) or inventory_hostname in groups["postgresql"]|default([]))
  tags: ['pgbouncer', 'postgresql', 'patroni', 'exporter']

- name: Info | Get informations of cluster
  include_tasks: _info.yml
  tags: info
