---

- name: Swap | Ensure swap exists
  ansible.builtin.command: swapon --show=SIZE --bytes --noheadings
  register: swap_exists
  changed_when: false
  when: swap_file_create | bool
  tags: ['swap']

- name: Swap | Display swap size
  ansible.builtin.debug:
    msg: "swap_size_mb: {{ (swap_exists.stdout_lines|map('trim')|map('int')|sum / 1024 / 1024)|round|int }}"
  when: swap_exists.stdout is defined and swap_exists.stdout | length > 1
  tags: ['swap']

- name: Swap | If the swap exists and the size is not equal to swap_file_size_mb
  block:
    - name: Disable all existing swaps
      ansible.builtin.command: swapoff --all

    - name: Swap | Remove swap from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: absent
        regexp: ' swap '

    - name: Swap | Remove swap file (if exists)
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        state: absent
  when: (swap_exists.stdout is defined and swap_exists.stdout | length > 1) and
        ((swap_exists.stdout_lines|map('trim')|map('int')|sum / 1024 / 1024)|round|int != swap_file_size_mb|int)
  tags: ['swap']

- name: Swap | If the swap does not exist
  block:
    - name: Swap | Create swap file
      ansible.builtin.command: |
        dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}
        creates='{{ swap_file_path }}'

    - name: Swap | Set permissions on swap file
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        owner: root
        group: root
        mode: 0600

    - name: Swap | Make swap file if necessary
      ansible.builtin.command: mkswap {{ swap_file_path }}
      register: mkswap_result

    - name: Swap | Run swapon on the swap file
      ansible.builtin.command: swapon {{ swap_file_path }}

    - name: Swap | Manage swap file entry in fstab
      ansible.builtin.mount:
        name: none
        src: "{{ swap_file_path }}"
        fstype: swap
        opts: sw
        state: present
  when: (swap_exists.stdout is defined and swap_exists.stdout | length < 1) or
        (swap_exists.stdout_lines is defined and (swap_exists.stdout_lines | map('trim') | map('int') | sum / 1024 / 1024) | round | int != swap_file_size_mb|int)
  tags: ['swap']
