---
# THP
- name: Start disable-transparent-huge-pages service
  ansible.builtin.systemd:
    daemon_reload: true
    name: disable-transparent-huge-pages
    state: restarted
    enabled: true
  listen: restart disable-thp


# IO Scheduler
- name: Start IO Scheduler service
  ansible.builtin.systemd:
    daemon_reload: true
    name: io-scheduler
    state: restarted
    enabled: true
  listen: restart io-scheduler


# HAProxy
- name: Restart HAProxy service
  ansible.builtin.systemd:
    daemon_reload: true
    name: haproxy
    enabled: true
    state: restarted
  listen: restart haproxy

- name: Check HAProxy is started and accepting connections
  ansible.builtin.wait_for:
    port: "{{ haproxy_listen_port.stats }}"
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  listen: restart haproxy


# Confd
- name: Restart Confd service
  ansible.builtin.systemd:
    daemon_reload: true
    name: confd
    enabled: true
    state: restarted
  listen: restart confd


# KeepAlived
- name: Restart KeepAlived service
  ansible.builtin.systemd:
    daemon_reload: true
    name: keepalived
    enabled: true
    state: restarted
  listen: restart keepalived

- name: Wait for cluster VIP to be running - {{ cluster_vip }}
  ansible.builtin.command: ip addr show
  register: ip_addr_result
  until: cluster_vip == '0.0.0.0' or cluster_vip in ip_addr_result.stdout
  retries: 30
  delay: 2
  changed_when: false
  failed_when: false
  listen: restart keepalived

- name: Restart KeepAlived exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: keepalived-exporter
    enabled: true
    state: restarted
  listen: restart keepalived-exporter

- name: Wait for port 9165 to become open on the host
  ansible.builtin.wait_for:
    port: 9165
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  listen: restart keepalived-exporter


# PGBouncer
- name: Restart PGBouncer service
  ansible.builtin.systemd:
    daemon_reload: true
    name: pgbouncer
    enabled: true
    state: restarted
  listen: restart pgbouncer

- name: Wait for port to become open on the host - {{ pgbouncer_listen_port }}
  ansible.builtin.wait_for:
    port: "{{ pgbouncer_listen_port }}"
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  listen: restart pgbouncer

- name: Reload PGBouncer service
  ansible.builtin.systemd:
    name: pgbouncer
    state: reloaded
  listen: reload pgbouncer
  failed_when: false

- name: Restart PGBouncer exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: pgbouncer-exporter
    enabled: true
    state: restarted
  listen: restart pgbouncer-exporter

- name: Wait for port 9127 to become open on the host
  ansible.builtin.wait_for:
    port: 9127
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  listen: restart pgbouncer-exporter
